CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(20) NOT NULL,
    starosta_id BIGINT
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT,
    username VARCHAR(255),
    patronymic VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    role VARCHAR(255),
    group_id BIGINT REFERENCES groups (id),
    teacher_uuid VARCHAR(255),
    CONSTRAINT uk_users_telegram_id UNIQUE (telegram_id),
    CONSTRAINT uk_users_teacher_uuid UNIQUE (teacher_uuid)
);

ALTER TABLE groups
    ADD COLUMN IF NOT EXISTS starosta_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.contype = 'f'
          AND c.conrelid = 'groups'::regclass
          AND c.confrelid = 'users'::regclass
          AND c.conkey = ARRAY[
              (SELECT attnum FROM pg_attribute
               WHERE attrelid = 'groups'::regclass AND attname = 'starosta_id')
          ]::SMALLINT[]
    ) THEN
        ALTER TABLE groups
            ADD CONSTRAINT fk_groups_starosta
            FOREIGN KEY (starosta_id) REFERENCES users (id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS teacher_groups (
    teacher_id BIGINT NOT NULL REFERENCES users (id),
    group_id BIGINT NOT NULL REFERENCES groups (id),
    CONSTRAINT pk_teacher_groups PRIMARY KEY (teacher_id, group_id)
);

CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id UUID,
    series_id UUID,
    group_id BIGINT REFERENCES groups (id),
    subject_name VARCHAR(255),
    lesson_type VARCHAR(255),
    teacher_id BIGINT REFERENCES users (id),
    classroom VARCHAR(255),
    lesson_date DATE,
    start_time TIME(6),
    end_time TIME(6),
    lesson_week INTEGER,
    control_sum VARCHAR(255),
    CONSTRAINT uk_schedule_occurrence UNIQUE (occurrence_id)
);

ALTER TABLE schedule
    ADD COLUMN IF NOT EXISTS occurrence_id UUID,
    ADD COLUMN IF NOT EXISTS series_id UUID;

UPDATE schedule
SET occurrence_id = gen_random_uuid()
WHERE occurrence_id IS NULL;

CREATE TABLE IF NOT EXISTS schedule_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id UUID,
    series_id UUID,
    client_request_id UUID,
    batch_request_id UUID,
    request_hash VARCHAR(64),
    operation VARCHAR(16),
    change_version BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    subject_name VARCHAR(255),
    lesson_type VARCHAR(255),
    teacher_name VARCHAR(255),
    classroom VARCHAR(255),
    old_lesson_date DATE,
    old_start_time TIME(6),
    old_end_time TIME(6),
    new_lesson_date DATE,
    new_start_time TIME(6),
    new_end_time TIME(6),
    description VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    old_control_sum VARCHAR(255),
    group_id BIGINT REFERENCES groups (id),
    author_id BIGINT REFERENCES users (id),
    CONSTRAINT uk_schedule_change_group_request UNIQUE (group_id, client_request_id),
    CONSTRAINT uk_schedule_change_occurrence_version UNIQUE (occurrence_id, change_version),
    CONSTRAINT uk_schedule_change_batch_occurrence UNIQUE (group_id, batch_request_id, occurrence_id)
);

ALTER TABLE schedule_changes
    ADD COLUMN IF NOT EXISTS occurrence_id UUID,
    ADD COLUMN IF NOT EXISTS series_id UUID,
    ADD COLUMN IF NOT EXISTS client_request_id UUID,
    ADD COLUMN IF NOT EXISTS batch_request_id UUID,
    ADD COLUMN IF NOT EXISTS request_hash VARCHAR(64),
    ADD COLUMN IF NOT EXISTS operation VARCHAR(16),
    ADD COLUMN IF NOT EXISTS change_version BIGINT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS author_id BIGINT;

CREATE TABLE IF NOT EXISTS absences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    schedule_id BIGINT NOT NULL REFERENCES schedule (id),
    date DATE,
    reason VARCHAR(255),
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS deadlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    uuid UUID,
    description TEXT,
    due_date DATE,
    group_id BIGINT REFERENCES groups (id),
    creator_id BIGINT REFERENCES users (id),
    notified_3_days BOOLEAN NOT NULL DEFAULT FALSE,
    notified_1_day BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    group_id BIGINT NOT NULL REFERENCES groups (id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_id UUID NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id),
    group_id BIGINT NOT NULL REFERENCES groups (id),
    description VARCHAR(255),
    from_date DATE NOT NULL,
    to_date DATE NOT NULL
);
