name: backend-ci

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/telegram-bot-starosta-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME:sha-${{ github.sha }} -t $IMAGE_NAME:latest .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:sha-${{ github.sha }}
          docker push $IMAGE_NAME:latest
  ssh-test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: ssh check
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          debug: true
          script: |
            whoami
            hostname
            uptime

  deploy:
    needs: ssh-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /ru/asem/bot
            docker compose up -d postgres
            for i in {1..30}; do
              if [ "$(docker inspect -f '{{json .State.Health.Status}}' $(docker compose ps -q postgres))" = "\"healthy\"" ]; then
                break
              fi
              sleep 3
            done

            docker compose pull backend
            docker compose up -d --no-deps backend

            for i in {1..30}; do
              if [ "$(docker inspect -f '{{json .State.Health.Status}}' $(docker compose ps -q backend))" = "\"healthy\"" ]; then
                break
              fi
              sleep 3
            done